# frozen_string_literal: true

require 'cgi'
require 'digest'
require 'fileutils'
require 'open3'

module RedmineProjectExplorer
  module PdfSequenceSupport
    PREFIX = 'project_explorer_png:'

    module_function

    # Convert a rendered Redmine <pre> Mermaid block to a locally generated
    # PNG image before RBPDF consumes the HTML.  RBPDF cannot render SVG
    # directly, so the plugin first renders SVG with its offline renderer and
    # then rasterizes that SVG to PNG with the local ImageMagick executable.
    def replace_sequence_blocks(html)
      source_html = html.to_s
      replaced = false

      result = source_html.gsub(%r{<pre\b[^>]*>.*?</pre>}mi) do |block|
        source = extract_source(block)
        unless source.match?(/\AsequenceDiagram\b/)
          next block
        end

        begin
          svg = RedmineProjectExplorer::SequenceSvgRenderer.new(source).render
          path = cache_png(svg)
          replaced = true
          %(<div style="text-align:center"><img src="#{PREFIX}#{CGI.escapeHTML(path)}" width="650" /></div>)
        rescue StandardError => e
          log("render failed: #{e.class}: #{e.message}")
          block
        end
      end

      log("sequence block replaced=#{replaced}")
      result
    end

    def extract_source(block)
      CGI.unescapeHTML(
        block.gsub(%r{</?code\b[^>]*>}mi, '')
             .gsub(%r{</?pre\b[^>]*>}mi, '')
             .gsub(/<br\s*\/?\s*>/i, "\n")
             .gsub(/<[^>]+>/, '')
      ).strip
    end

    def cache_root
      Rails.root.join('tmp', 'redmine_project_explorer_pdf').to_s
    end

    def cache_png(svg)
      FileUtils.mkdir_p(cache_root)
      digest = Digest::SHA256.hexdigest(svg)
      svg_path = File.join(cache_root, "#{digest}.svg")
      png_path = File.join(cache_root, "#{digest}.png")

      File.binwrite(svg_path, svg) unless File.exist?(svg_path)
      return png_path if File.file?(png_path) && File.size?(png_path)

      # Use argument-array execution (not a shell command) so generated paths
      # are passed safely.  All rendering remains local to the Redmine host.
      stdout, stderr, status = Open3.capture3(
        'magick',
        '-background', 'white',
        '-density', '144',
        svg_path,
        '-alpha', 'remove',
        '-alpha', 'off',
        png_path
      )

      unless status.success? && File.file?(png_path) && File.size?(png_path)
        FileUtils.rm_f(png_path)
        message = stderr.to_s.strip
        message = stdout.to_s.strip if message.empty?
        raise "ImageMagick SVG->PNG failed (status=#{status.exitstatus}): #{message}"
      end

      log("rasterized SVG to PNG #{png_path}")
      png_path
    end

    def log(message)
      Rails.logger.info("[Project Explorer PDF Mermaid] #{message}") if defined?(Rails) && Rails.respond_to?(:logger)
    rescue StandardError
      nil
    end
  end

  # Patch pdf_format_text at the actual module that defines the method.
  module IssuesPdfHelperPatch
    def pdf_format_text(object, attribute)
      html = super
      RedmineProjectExplorer::PdfSequenceSupport.replace_sequence_blocks(html)
    end
  end

  # Redmine's ITCPDF resolves <img src="..."> through get_image_filename.
  # Permit only PNG files generated by this plugin under Rails.root/tmp.
  module ItcpdfProjectExplorerImagePatch
    def get_image_filename(attrname)
      value = attrname.to_s
      prefix = RedmineProjectExplorer::PdfSequenceSupport::PREFIX

      if value.start_with?(prefix)
        requested = File.expand_path(CGI.unescapeHTML(value.delete_prefix(prefix)))
        root = File.expand_path(RedmineProjectExplorer::PdfSequenceSupport.cache_root)
        if requested.start_with?(root + File::SEPARATOR) &&
           requested.end_with?('.png') && File.file?(requested)
          RedmineProjectExplorer::PdfSequenceSupport.log("using local PNG #{requested}")
          return requested
        end
      end

      super
    end
  end
end

# Install the patches immediately during plugin initialization. In production,
# registering only a to_prepare callback can be too late. apply! is idempotent,
# so it is also called from to_prepare for development reloads.
module RedmineProjectExplorer
  module PdfPatchInstaller
    module_function

    def apply!
      require_dependency 'issues_helper'
      require_dependency Rails.root.join('lib/redmine/export/pdf/issues_pdf_helper').to_s
      require_dependency Rails.root.join('lib/redmine/export/pdf').to_s

      pdf_helper = Redmine::Export::PDF::IssuesPdfHelper
      pdf_helper.prepend(RedmineProjectExplorer::IssuesPdfHelperPatch) unless
        pdf_helper.ancestors.include?(RedmineProjectExplorer::IssuesPdfHelperPatch)

      IssuesHelper.prepend(RedmineProjectExplorer::IssuesPdfHelperPatch) unless
        IssuesHelper.ancestors.include?(RedmineProjectExplorer::IssuesPdfHelperPatch)

      pdf_class = Redmine::Export::PDF::ITCPDF
      pdf_class.prepend(RedmineProjectExplorer::ItcpdfProjectExplorerImagePatch) unless
        pdf_class.ancestors.include?(RedmineProjectExplorer::ItcpdfProjectExplorerImagePatch)

      RedmineProjectExplorer::PdfSequenceSupport.log(
        "patch active: issues_helper=#{IssuesHelper.ancestors.include?(RedmineProjectExplorer::IssuesPdfHelperPatch)} " \
        "pdf_helper=#{pdf_helper.ancestors.include?(RedmineProjectExplorer::IssuesPdfHelperPatch)} " \
        "itcpdf=#{pdf_class.ancestors.include?(RedmineProjectExplorer::ItcpdfProjectExplorerImagePatch)}"
      )
      true
    rescue StandardError => e
      RedmineProjectExplorer::PdfSequenceSupport.log(
        "patch install failed: #{e.class}: #{e.message}"
      )
      false
    end
  end
end

RedmineProjectExplorer::PdfPatchInstaller.apply!

Rails.configuration.to_prepare do
  RedmineProjectExplorer::PdfPatchInstaller.apply!
end
